// Razorpay Payment Integration
// IMPORTANT: Replace these with your actual Razorpay keys from https://dashboard.razorpay.com/
// Get your keys from: Settings → API Keys in Razorpay Dashboard
// Test Mode: Use keys starting with 'rzp_test_'
// Live Mode: Use keys starting with 'rzp_live_'
const RAZORPAY_KEY_ID = 'rzp_test_SA0i0IMuxznVxV'; // Replace with your Razorpay Key ID
const RAZORPAY_KEY_SECRET = 'MaamfeF85nVABBi0jTmla0l1'; // Replace with your Razorpay Secret Key (keep this secure on backend)

// Check if keys are configured
if (RAZORPAY_KEY_ID === 'rzp_test_SA0i0IMuxznVxV' || RAZORPAY_KEY_ID === '') {
    console.warn('⚠️ Razorpay Key ID not configured! Please update RAZORPAY_KEY_ID in js/payment.js');
}

// Payment configuration
let paymentOrderData = null;

/**
 * Initialize Razorpay payment
 * @param {Object} orderData - Order details including amount, orderId, etc.
 */
function initializeRazorpayPayment(orderData) {
    paymentOrderData = orderData;

    const options = {
        key: RAZORPAY_KEY_ID,
        amount: orderData.payment.total * 100, // Amount in paise (multiply by 100)
        currency: 'INR',
        name: 'E-Commerce Store',
        description: `Order #${orderData.orderId}`,
        image: 'https://via.placeholder.com/150', // Your logo URL
        order_id: null, // This will be generated by your backend
        handler: function (response) {
            // Payment successful
            handlePaymentSuccess(response);
        },
        prefill: {
            name: orderData.shipping.fullName,
            email: orderData.shipping.email,
            contact: orderData.shipping.phone
        },
        notes: {
            address: `${orderData.shipping.address}, ${orderData.shipping.city}, ${orderData.shipping.state} ${orderData.shipping.postalCode}`,
            order_id: orderData.orderId
        },
        theme: {
            color: '#4CAF50'
        },
        modal: {
            ondismiss: function () {
                // User closed the payment modal
                handlePaymentFailure('Payment cancelled by user');
            }
        }
    };

    // For production, you should create an order on your backend first
    // and get the order_id from Razorpay. For now, we'll use direct payment
    const razorpay = new Razorpay(options);

    razorpay.on('payment.failed', function (response) {
        handlePaymentFailure(response.error.description || 'Payment failed');
    });

    razorpay.open();
}

/**
 * Handle successful payment
 * @param {Object} response - Razorpay payment response
 */
function handlePaymentSuccess(response) {
    // Update order data with payment information
    paymentOrderData.payment = {
        ...paymentOrderData.payment,
        razorpay_payment_id: response.razorpay_payment_id,
        razorpay_order_id: response.razorpay_order_id,
        razorpay_signature: response.razorpay_signature,
        status: 'paid',
        paid_at: new Date().toISOString()
    };

    // Complete the order
    completeOrder(paymentOrderData);

    // Customer notification: order placed & payment confirmed
    try {
        if (typeof window.addCustomerNotification === 'function') {
            window.addCustomerNotification({
                type: 'order',
                title: 'Order Confirmed',
                message: `Your order ${paymentOrderData.orderId} has been placed successfully.`,
                icon: 'fa-receipt',
                color: 'green'
            });
        }
    } catch (e) {
        console.error('Notification error:', e);
    }

    // Show success message
    showToast('Payment successful! Order placed.');

    // Show success modal
    showPaymentSuccessModal(paymentOrderData);
}

/**
 * Handle payment failure
 * @param {String} errorMessage - Error message
 */
function handlePaymentFailure(errorMessage) {
    console.error('Payment failed:', errorMessage);
    showToast(`Payment failed: ${errorMessage}`);

    // Show error modal
    showPaymentErrorModal(errorMessage);
}

/**
 * Complete the order after successful payment
 * @param {Object} orderData - Complete order data
 */
function completeOrder(orderData) {
    // Update order status to processing after successful payment
    orderData.status = 'processing';
    orderData.payment.status = 'paid';

    // Save order to localStorage
    const orders = JSON.parse(localStorage.getItem('orders')) || [];
    orders.unshift(orderData);
    localStorage.setItem('orders', JSON.stringify(orders));

    // Add notification for admin
    const notifications = JSON.parse(localStorage.getItem('notifications')) || [];
    notifications.unshift({
        message: `New paid order received: ${orderData.orderId} - ₹${orderData.payment.total.toFixed(2)}`,
        icon: 'fa-shopping-cart',
        timestamp: new Date().toISOString(),
        type: 'order'
    });
    localStorage.setItem('notifications', JSON.stringify(notifications));

    // Clear cart
    if (typeof resetCart === 'function') {
        resetCart();
    }

    // Update UI if on profile page
    if (typeof renderApp === 'function' && typeof currentPage !== 'undefined' && currentPage === 'profile') {
        setTimeout(() => {
            renderApp();
        }, 1000);
    }
}

/**
 * Show payment success modal
 * @param {Object} orderData - Order data
 */
function showPaymentSuccessModal(orderData) {
    const modal = document.createElement('div');
    modal.id = 'paymentSuccessModal';
    modal.className = 'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50';
    modal.innerHTML = `
        <div class="bg-white rounded-lg p-6 w-[90%] max-w-md">
            <div class="text-center">
                <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <i class="fas fa-check text-3xl text-green-500"></i>
                </div>
                <h3 class="text-xl font-bold mb-2">Payment Successful!</h3>
                <p class="text-gray-600 mb-4">Your order has been placed successfully.</p>
                <div class="bg-gray-50 rounded-lg p-4 mb-4 text-left">
                    <p class="text-sm text-gray-600 mb-1"><strong>Order ID:</strong> ${orderData.orderId}</p>
                    <p class="text-sm text-gray-600 mb-1"><strong>Payment ID:</strong> ${orderData.payment.razorpay_payment_id}</p>
                    <p class="text-sm text-gray-600"><strong>Amount:</strong> ₹${orderData.payment.total.toFixed(2)}</p>
                </div>
                <p class="text-gray-600 mb-6">We'll send you a confirmation email shortly.</p>
                <div class="flex gap-3">
                    <button onclick="closePaymentModal(); if(typeof navigate==='function') navigate('profile');" 
                            class="flex-1 bg-gray-100 text-gray-700 py-3 rounded-lg font-semibold hover:bg-gray-200">
                        View Order
                    </button>
                    <button onclick="closePaymentModal(); navigate('home')" 
                            class="flex-1 bg-green-500 text-white py-3 rounded-lg font-semibold hover:bg-green-600">
                        Continue Shopping
                    </button>
                </div>
            </div>
        </div>
    `;
    document.body.appendChild(modal);
}

/**
 * Show payment error modal
 * @param {String} errorMessage - Error message
 */
function showPaymentErrorModal(errorMessage) {
    const modal = document.createElement('div');
    modal.id = 'paymentErrorModal';
    modal.className = 'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50';
    modal.innerHTML = `
        <div class="bg-white rounded-lg p-6 w-[90%] max-w-md">
            <div class="text-center">
                <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <i class="fas fa-times text-3xl text-red-500"></i>
                </div>
                <h3 class="text-xl font-bold mb-2">Payment Failed</h3>
                <p class="text-gray-600 mb-6">${errorMessage}</p>
                <div class="flex gap-3">
                    <button onclick="closePaymentModal()" 
                            class="flex-1 bg-gray-100 text-gray-700 py-3 rounded-lg font-semibold hover:bg-gray-200">
                        Close
                    </button>
                    <button onclick="closePaymentModal(); retryPayment()" 
                            class="flex-1 bg-green-500 text-white py-3 rounded-lg font-semibold hover:bg-green-600">
                        Try Again
                    </button>
                </div>
            </div>
        </div>
    `;
    document.body.appendChild(modal);
}

/**
 * Close payment modal
 */
function closePaymentModal() {
    const successModal = document.getElementById('paymentSuccessModal');
    const errorModal = document.getElementById('paymentErrorModal');
    if (successModal) successModal.remove();
    if (errorModal) errorModal.remove();
}

/**
 * Retry payment
 */
function retryPayment() {
    if (paymentOrderData) {
        initializeRazorpayPayment(paymentOrderData);
    }
}


// Note: For production use, you should:
// 1. Create a backend API endpoint to create Razorpay orders
// 2. Store RAZORPAY_KEY_SECRET on the backend only
// 3. Verify payment signatures on the backend
// 4. Handle webhooks for payment status updates
