const mongoose = require('mongoose');
const dotenv = require('dotenv');
const connectDB = require('./config/db');
const Product = require('./models/Product');

dotenv.config({ path: require('path').resolve(__dirname, '../.env') });
connectDB();

const defaultProducts = [
    // Electronics
    {
        id: 1,
        name: 'AirPods Pro',
        price: 24900,
        category: 'Electronics',
        rating: { rate: 4.8, count: 120 },
        image: '/images/p1.jpg',
        stock: 50,
        description: 'Active noise cancellation having transparency mode. Spatial audio.',
    },
    {
        id: 2,
        name: 'MacBook Air M2',
        price: 114900,
        category: 'Electronics',
        rating: { rate: 4.9, count: 85 },
        image: '/images/p2.jpg',
        stock: 20,
        description: 'Supercharged by M2 chip. Thin, light, and powerful.',
    },
    {
        id: 3,
        name: 'Sony WH-1000XM5',
        price: 29990,
        category: 'Electronics',
        rating: { rate: 4.7, count: 200 },
        image: '/images/p3.jpg',
        stock: 35,
        description: 'Industry leading noise canceling headphones.',
    },
    {
        id: 4,
        name: 'Samsung Galaxy S24 Ultra',
        price: 129999,
        category: 'Electronics',
        rating: { rate: 4.8, count: 150 },
        image: '/images/p4.jpg',
        stock: 15,
        description: 'Titanium frame, AI features, and S-Pen.',
    },
    {
        id: 5,
        name: 'iPad Air 5th Gen',
        price: 54900,
        category: 'Electronics',
        rating: { rate: 4.6, count: 90 },
        image: '/images/p5.jpg',
        stock: 40,
        description: 'Supercharged by the Apple M1 chip.',
    },
    {
        id: 6,
        name: 'GoPro Hero 12 Black',
        price: 39990,
        category: 'Electronics',
        rating: { rate: 4.5, count: 60 },
        image: '/images/p6.jpg',
        stock: 25,
        description: 'Unbelievable image quality and stabilization.',
    },
    {
        id: 7,
        name: 'PlayStation 5 Console',
        price: 54990,
        category: 'Electronics',
        rating: { rate: 4.9, count: 300 },
        image: '/images/p7.jpg',
        stock: 10,
        description: 'Play Has No Limits. Lightning fast loading.',
    },
    // Fashion
    {
        id: 11,
        name: 'Levi\'s Men\'s 501 Original',
        price: 3599,
        category: 'Fashion',
        rating: { rate: 4.4, count: 400 },
        image: '/images/p11.jpg',
        stock: 60,
        description: 'The original button fly jean.',
    },
    {
        id: 12,
        name: 'Adidas Ultraboost Light',
        price: 13999,
        category: 'Fashion',
        rating: { rate: 4.7, count: 180 },
        image: '/images/p12.jpg',
        stock: 45,
        description: 'Lightest Ultraboost ever made.',
    },
    {
        id: 13,
        name: 'Ray-Ban Aviator Sunglasses',
        price: 8990,
        category: 'Fashion',
        rating: { rate: 4.6, count: 220 },
        image: '/images/p13.jpg',
        stock: 30,
        description: 'Classic teardrop shape.',
    },
    {
        id: 14,
        name: 'Puma Men\'s Hoodie',
        price: 2499,
        category: 'Fashion',
        rating: { rate: 4.3, count: 150 },
        image: '/images/p14.jpg',
        stock: 55,
        description: 'Comfortable cotton blend hoodie.',
    },
    {
        id: 15,
        name: 'Zara Floral Summer Dress',
        price: 3990,
        category: 'Fashion',
        rating: { rate: 4.5, count: 110 },
        image: '/images/p15.jpg',
        stock: 40,
        description: 'Lightweight and flowy for summer.',
    },
    {
        id: 16,
        name: 'H&M Denim Jacket',
        price: 3999,
        category: 'Fashion',
        rating: { rate: 4.4, count: 130 },
        image: '/images/p16.jpg',
        stock: 35,
        description: 'Classic denim jacket with button closure.',
    },
    // Beauty
    {
        id: 17,
        name: 'Maybelline Matte Lipstick',
        price: 499,
        category: 'Beauty',
        rating: { rate: 4.3, count: 500 },
        image: '/images/p17.jpg',
        stock: 100,
        description: 'Long lasting matte finish.',
    },
    {
        id: 18,
        name: 'Dyson Airwrap Styler',
        price: 45900,
        category: 'Beauty',
        rating: { rate: 4.8, count: 250 },
        image: '/images/p18.jpg',
        stock: 15,
        description: 'Curl. Shape. Smooth and hide flyaways.',
    },
    {
        id: 19,
        name: 'CeraVe Moisturizing Cream',
        price: 1299,
        category: 'Beauty',
        rating: { rate: 4.7, count: 450 },
        image: '/images/p19.jpg',
        stock: 80,
        description: 'For normal to dry skin.',
    },
    {
        id: 20,
        name: 'MAC Studio Fix Fluid',
        price: 3300,
        category: 'Beauty',
        rating: { rate: 4.6, count: 320 },
        image: '/images/p20.jpg',
        stock: 40,
        description: '24-hour wear breathable foundation.',
    },
    // Home & Kitchen
    {
        id: 21,
        name: 'Philips Digital Air Fryer',
        price: 8999,
        category: 'Home & Kitchen',
        rating: { rate: 4.7, count: 180 },
        image: '/images/p21.jpg',
        stock: 30,
        description: 'Great tasting fries with up to 90% less fat.',
    },
    {
        id: 22,
        name: 'Prestige Pressure Cooker',
        price: 1999,
        category: 'Home & Kitchen',
        rating: { rate: 4.4, count: 210 },
        image: '/images/p22.jpg',
        stock: 50,
        description: 'Durable stainless steel cooker.',
    },
    {
        id: 23,
        name: 'Milton Casserole Set',
        price: 1499,
        category: 'Home & Kitchen',
        rating: { rate: 4.3, count: 160 },
        image: '/images/p23.jpg',
        stock: 45,
        description: 'Keeps food hot for hours.',
    },
    {
        id: 24,
        name: 'IKEA TERTIAL Work Lamp',
        price: 1299,
        category: 'Home & Kitchen',
        rating: { rate: 4.6, count: 95 },
        image: '/images/p24.jpg',
        stock: 60,
        description: 'Adjustable arm and head.',
    },
    // Toys
    {
        id: 28,
        name: 'LEGO Star Wars Y-Wing',
        price: 6999,
        category: 'Toys',
        rating: { rate: 4.9, count: 140 },
        image: '/images/p28.jpg',
        stock: 20,
        description: 'Detailed replica Model.',
    },
    {
        id: 29,
        name: 'Barbie Dreamhouse',
        price: 11999,
        category: 'Toys',
        rating: { rate: 4.8, count: 110 },
        image: '/images/p29.jpg',
        stock: 12,
        description: '3 stories, 8 rooms, 70+ accessories.',
    },
    {
        id: 30,
        name: 'Monopoly Classic Game',
        price: 999,
        category: 'Toys',
        rating: { rate: 4.7, count: 500 },
        image: '/images/p30.jpg',
        stock: 100,
        description: 'The fast-dealing property trading game.',
    },
    {
        id: 31,
        name: 'Nerf Elite 2.0 Commander',
        price: 1499,
        category: 'Toys',
        rating: { rate: 4.5, count: 230 },
        image: '/images/p31.jpg',
        stock: 50,
        description: '6-dart rotating drum.',
    },
    // Sports
    {
        id: 35,
        name: 'Yonex Badminton Racket',
        price: 2499,
        category: 'Sports',
        rating: { rate: 4.4, count: 150 },
        image: '/images/p35.jpg',
        stock: 40,
        description: 'Lightweight graphite frame.',
    },
    {
        id: 36,
        name: 'Premium Yoga Mat',
        price: 999,
        category: 'Sports',
        rating: { rate: 4.5, count: 190 },
        image: '/images/p36.jpg',
        stock: 80,
        description: 'Non-slip surface for yoga and gym.',
    },
    {
        id: 37,
        name: 'Hex Dumbbells (5kg Pair)',
        price: 1999,
        category: 'Sports',
        rating: { rate: 4.6, count: 85 },
        image: '/images/p37.jpg',
        stock: 30,
        description: 'Rubber encased hexagonal dumbbells.',
    },
    {
        id: 38,
        name: 'Spalding Basketball',
        price: 1899,
        category: 'Sports',
        rating: { rate: 4.5, count: 120 },
        image: '/images/p38.jpg',
        stock: 40,
        description: 'Official size and weight.',
    },
    // Books
    {
        id: 41,
        name: 'Atomic Habits',
        price: 599,
        category: 'Books',
        rating: { rate: 4.9, count: 1000 },
        image: '/images/p41.jpg',
        stock: 150,
        description: 'Tiny Changes, Remarkable Results.',
    },
    {
        id: 42,
        name: 'The Psychology of Money',
        price: 399,
        category: 'Books',
        rating: { rate: 4.8, count: 900 },
        image: '/images/p42.jpg',
        stock: 120,
        description: 'Timeless lessons on wealth, greed, and happiness.',
    },
    {
        id: 43,
        name: 'Harry Potter Box Set',
        price: 2999,
        category: 'Books',
        rating: { rate: 5.0, count: 500 },
        image: '/images/p43.jpg',
        stock: 30,
        description: 'Complete collection of 7 books.',
    },
    // Furniture
    {
        id: 47,
        name: 'Ergonomic Office Chair',
        price: 8999,
        category: 'Furniture',
        rating: { rate: 4.5, count: 80 },
        image: '/images/p47.jpg',
        stock: 20,
        description: 'Mesh back with lumbar support.',
    },
    {
        id: 48,
        name: 'Wooden Coffee Table',
        price: 4999,
        category: 'Furniture',
        rating: { rate: 4.4, count: 60 },
        image: '/images/p48.jpg',
        stock: 15,
        description: 'Solid wood with modern design.',
    },
    {
        id: 49,
        name: 'Bean Bag XXL',
        price: 1999,
        category: 'Furniture',
        rating: { rate: 4.2, count: 90 },
        image: '/images/p49.jpg',
        stock: 25,
        description: 'Comfortable seating for lounge.',
    }
];

const importData = async () => {
    try {
        await Product.deleteMany();

        await Product.insertMany(defaultProducts);

        console.log('Data Imported!');
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

importData();
